// @vitest-environment node
/**
 * The end-to-end question no jsdom test can answer: after the desktop rewriter
 * and the artifact CSP, does the Mermaid library actually become available to
 * the figure, and does a diagram appear?
 *
 * Everything here is real except the network: the document is a genuine CDN-mode
 * `render_mermaid` output (regenerated by the Rust contract test), the rewriter
 * is the one `main.ts` calls, the CSP is the one `ArtifactViewer` injects, and
 * the library is the vendored copy the offline path inlines. Requests to the
 * CDN are aborted so the run is hermetic — which is also the honest simulation,
 * since the artifact CSP forbids them in production anyway.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium, type Browser } from 'playwright';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { inlineArtifactCdnAssets } from './artifactCdnAssets';
import { injectArtifactBrowserCsp } from './artifactSecurity';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');

const MERMAID_CDN_URL = 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js';
const VENDORED_MERMAID = resolve(
  repoRoot,
  'crates/biorouter-mcp/src/autovisualiser/templates/assets/mermaid.min.js'
);
const CDN_FIXTURE = resolve(here, '__fixtures__/autovis-mermaid-cdn.html');

/** Serve the vendored library instead of reaching the CDN. */
const fetchVendored = async (url: string): Promise<string> => {
  if (url !== MERMAID_CDN_URL) throw new Error(`unexpected asset request: ${url}`);
  return readFileSync(VENDORED_MERMAID, 'utf-8');
};

/**
 * Launch whichever Chromium build this machine downloaded. Playwright's default
 * is the headless shell, which is a *separate* download from full Chromium, so
 * a tree that only has one of the two must not be reported as "no browser".
 */
const launchChromium = async (): Promise<Browser | null> => {
  for (const options of [{}, { channel: 'chromium' }] as const) {
    try {
      return await chromium.launch(options);
    } catch {
      // try the next build
    }
  }
  return null;
};

describe('a CDN-mode Mermaid figure in a real browser', () => {
  let browser: Browser | null = null;

  beforeAll(async () => {
    browser = await launchChromium();
    if (!browser) {
      // Say so out loud: a silently skipped browser test reads as a passing one.
      console.warn(
        'No Playwright Chromium build found — skipping the artifact CSP tests. ' +
          'Run `npx playwright install chromium` to enable them.'
      );
    }
  }, 120_000);

  afterAll(async () => {
    await browser?.close();
  });

  /** Render a prepared artifact document under the real artifact CSP. */
  const open = async (html: string) => {
    const page = await browser!.newPage();
    // Nothing may reach the network: the artifact CSP blocks it in production,
    // and a test that quietly downloaded 3.5 MB would be measuring the CDN.
    await page.route('**/cdn.jsdelivr.net/**', (route) => route.abort());
    await page.setContent(injectArtifactBrowserCsp(html), { waitUntil: 'load' });
    return page;
  };

  it('defines window.mermaid and draws the diagram', async (ctx) => {
    // Playwright's browsers are a separate download (`npx playwright install
    // chromium`). Skipping beats a red suite on a machine that has not fetched
    // them; the Rust contract test guards the wiring unconditionally.
    if (!browser) return ctx.skip();
    const prepared = await inlineArtifactCdnAssets(
      readFileSync(CDN_FIXTURE, 'utf-8'),
      fetchVendored
    );

    // The browser assertions come first deliberately: what this guards is "the
    // library never becomes available in the renderer", so that is what a
    // regression should report — not a string match on the document.
    const page = await open(prepared);
    try {
      await expect
        .poll(
          () => page.evaluate(() => typeof (window as unknown as Record<string, unknown>).mermaid),
          { timeout: 15_000 }
        )
        .toBe('object');
      await page.waitForSelector('#mermaidTarget svg', { timeout: 15_000 });
      expect(await page.locator('#mermaidTarget svg').count()).toBe(1);
      expect(await page.locator('[role="alert"]').count()).toBe(0);
    } finally {
      await page.close();
    }
    expect(prepared).not.toContain('cdn.jsdelivr.net');
  }, 60_000);

  it('fails when the library is emitted as an ESM import the rewriter cannot reach', async (ctx) => {
    if (!browser) return ctx.skip();
    // The shape this bug shipped in. Kept as a negative control so a harness
    // that silently stopped exercising the CSP would be noticed.
    const esmImport = readFileSync(CDN_FIXTURE, 'utf-8').replace(
      /<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/mermaid@11\/dist\/mermaid\.min\.js"[^>]*><\/script>/,
      `<script type="module">import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/+esm';window.mermaid=mermaid;</script>`
    );
    expect(esmImport).toContain("+esm'");

    const prepared = await inlineArtifactCdnAssets(esmImport, fetchVendored);
    // The rewriter leaves it alone — that is the defect, not a test artefact.
    expect(prepared).toContain('+esm');

    const page = await open(prepared);
    try {
      await page.waitForSelector('[role="alert"]', { timeout: 30_000 });
      expect(await page.locator('#mermaidTarget svg').count()).toBe(0);
    } finally {
      await page.close();
    }
  }, 90_000);
});
