// @vitest-environment node
/**
 * The end-to-end question no jsdom test can answer: after the desktop rewriter
 * and the artifact CSP, does the Mermaid library actually become available to
 * the figure, and does a diagram appear?
 *
 * Everything here is real except the network: the document is a genuine CDN-mode
 * `render_mermaid` output (regenerated by the Rust contract test), the rewriter
 * is the one `main.ts` calls, the CSP is the one `ArtifactViewer` injects, and
 * the library is the vendored copy the offline path inlines. Requests to the
 * CDN are aborted so the run is hermetic — which is also the honest simulation,
 * since the artifact CSP forbids them in production anyway.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium, type Browser, type BrowserServer } from 'playwright';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { inlineArtifactCdnAssets } from './artifactCdnAssets';
import { injectArtifactBrowserCsp } from './artifactSecurity';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');

const MERMAID_CDN_URL = 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js';
const VENDORED_MERMAID = resolve(
  repoRoot,
  'crates/biorouter-mcp/src/autovisualiser/templates/assets/mermaid.min.js'
);
const CDN_FIXTURE = resolve(here, '__fixtures__/autovis-mermaid-cdn.html');

/** Serve the vendored library instead of reaching the CDN. */
const fetchVendored = async (url: string): Promise<string> => {
  if (url !== MERMAID_CDN_URL) throw new Error(`unexpected asset request: ${url}`);
  return readFileSync(VENDORED_MERMAID, 'utf-8');
};

/**
 * Every step of teardown gets this long, and no longer.
 *
 * ⚠ Chosen so the WHOLE hook — disconnect, close, kill, reap — is strictly
 * bounded well under `HOOK_TIMEOUT_MS` (30s). Three steps at 5s is 15s worst
 * case, which leaves the runner's own limit as a backstop rather than as the
 * thing that fires.
 */
const TEARDOWN_STEP_MS = 5_000;

/** Resolve `true` if `work` settled within `ms`, `false` if it ran out of time. */
const settledWithin = async (work: Promise<unknown>, ms: number): Promise<boolean> => {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const expired = new Promise<false>((resolve) => {
    timer = setTimeout(() => resolve(false), ms);
    // Never hold the loop open on account of the watchdog itself.
    (timer as unknown as { unref?: () => void }).unref?.();
  });
  try {
    // A rejected close is still a settled one: the point here is elapsed time,
    // and a browser that refused to close is handled by the caller's next step.
    return (
      (await Promise.race([
        work.then(
          () => true,
          () => true
        ),
        expired,
      ])) !== false
    );
  } finally {
    if (timer) clearTimeout(timer);
  }
};

/**
 * Launch whichever Chromium build this machine downloaded. Playwright's default
 * is the headless shell, which is a *separate* download from full Chromium, so
 * a tree that only has one of the two must not be reported as "no browser".
 *
 * ⚠ **`launchServer` + `connect`, not `launch`, and the reason is teardown.**
 * A `Browser` from `chromium.launch()` exposes no handle on the Chromium
 * process, so `browser.close()` is the ONLY way to end it — and when that call
 * is slow there is nothing left to do but wait for it. Under load it is slow:
 * with the machine saturated, `close()` blocked past the 30s hook limit while
 * both tests had already passed, so the file failed with ZERO failing tests and
 * `npm run test:run` exited 1 for a reason no test name could explain. A
 * `BrowserServer` hands back `process()`, which makes the last resort a SIGKILL
 * instead of an unbounded await.
 */
const launchChromium = async (): Promise<{ server: BrowserServer; browser: Browser } | null> => {
  for (const options of [{}, { channel: 'chromium' }] as const) {
    let server: BrowserServer | null = null;
    try {
      server = await chromium.launchServer(options);
      return { server, browser: await chromium.connect(server.wsEndpoint()) };
    } catch {
      // Launched but could not be connected to: end it here rather than leaking
      // a Chromium for the next option to sit beside.
      if (server) await settledWithin(server.close(), TEARDOWN_STEP_MS);
      // try the next build
    }
  }
  return null;
};

describe('a CDN-mode Mermaid figure in a real browser', () => {
  let browser: Browser | null = null;
  let server: BrowserServer | null = null;

  beforeAll(async () => {
    // Launched ONCE. A second launch would strand the first browser with no
    // handle left to close it by.
    if (browser) return;
    const launched = await launchChromium();
    browser = launched?.browser ?? null;
    server = launched?.server ?? null;
    if (!browser) {
      // Say so out loud: a silently skipped browser test reads as a passing one.
      console.warn(
        'No Playwright Chromium build found — skipping the artifact CSP tests. ' +
          'Run `npx playwright install chromium` to enable them.'
      );
    }
  }, 120_000);

  /**
   * Bounded, and closed exactly once.
   *
   * The handles are nulled BEFORE anything is awaited, so a re-entered hook
   * cannot start a second shutdown of the same browser — and so a later
   * `browser` read cannot hand a test a connection that is being torn down.
   */
  afterAll(async () => {
    const connection = browser;
    const launched = server;
    browser = null;
    server = null;

    if (connection) await settledWithin(connection.close(), TEARDOWN_STEP_MS);
    if (!launched) return;

    if (await settledWithin(launched.close(), TEARDOWN_STEP_MS)) return;

    // Still up. Stop asking.
    launched.process().kill('SIGKILL');
    await settledWithin(launched.close(), TEARDOWN_STEP_MS);
  });

  /** Render a prepared artifact document under the real artifact CSP. */
  const open = async (html: string) => {
    const page = await browser!.newPage();
    // Nothing may reach the network: the artifact CSP blocks it in production,
    // and a test that quietly downloaded 3.5 MB would be measuring the CDN.
    await page.route('**/cdn.jsdelivr.net/**', (route) => route.abort());
    await page.setContent(injectArtifactBrowserCsp(html), { waitUntil: 'load' });
    return page;
  };

  it('defines window.mermaid and draws the diagram', async (ctx) => {
    // Playwright's browsers are a separate download (`npx playwright install
    // chromium`). Skipping beats a red suite on a machine that has not fetched
    // them; the Rust contract test guards the wiring unconditionally.
    if (!browser) return ctx.skip();
    const prepared = await inlineArtifactCdnAssets(
      readFileSync(CDN_FIXTURE, 'utf-8'),
      fetchVendored
    );

    // The browser assertions come first deliberately: what this guards is "the
    // library never becomes available in the renderer", so that is what a
    // regression should report — not a string match on the document.
    const page = await open(prepared);
    try {
      await expect
        .poll(
          () => page.evaluate(() => typeof (window as unknown as Record<string, unknown>).mermaid),
          { timeout: 15_000 }
        )
        .toBe('object');
      await page.waitForSelector('#mermaidTarget svg', { timeout: 15_000 });
      expect(await page.locator('#mermaidTarget svg').count()).toBe(1);
      expect(await page.locator('[role="alert"]').count()).toBe(0);
    } finally {
      await page.close();
    }
    expect(prepared).not.toContain('cdn.jsdelivr.net');
  }, 60_000);

  it('fails when the library is emitted as an ESM import the rewriter cannot reach', async (ctx) => {
    if (!browser) return ctx.skip();
    // The shape this bug shipped in. Kept as a negative control so a harness
    // that silently stopped exercising the CSP would be noticed.
    const esmImport = readFileSync(CDN_FIXTURE, 'utf-8').replace(
      /<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/mermaid@11\/dist\/mermaid\.min\.js"[^>]*><\/script>/,
      `<script type="module">import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/+esm';window.mermaid=mermaid;</script>`
    );
    expect(esmImport).toContain("+esm'");

    const prepared = await inlineArtifactCdnAssets(esmImport, fetchVendored);
    // The rewriter leaves it alone — that is the defect, not a test artefact.
    expect(prepared).toContain('+esm');

    const page = await open(prepared);
    try {
      await page.waitForSelector('[role="alert"]', { timeout: 30_000 });
      expect(await page.locator('#mermaidTarget svg').count()).toBe(0);
    } finally {
      await page.close();
    }
  }, 90_000);
});
