blank_issues_enabled: false
contact_links:
  - name: BioRouter Discussions
    url: https://github.com/BaranziniLab/biorouter/discussions
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/BaranziniLab/BioRouter/security/policy
    about: Please report security vulnerabilities here.
