/**
 * DR-26's third axis, as the renderer reads it (issue #56).
 *
 * The tier answers *how sensitive is this?*; affiliation answers *under whose
 * agreements?*, and the two do not compose — a HIPAA-compliant LLM approved at
 * one institution has no blanket permission over another institution's PHI. Both
 * axes have been decided in the daemon since Task 48; until now the only
 * renderer file that so much as named an affiliation was the card that turns a
 * *refused* tool call into an accept button, so a user learned their chat's
 * institution only after something had already failed. This module is the
 * vocabulary the pre-flight badges read.
 *
 * ⚠ **Read-only, in the strongest sense.** Nothing here is ever sent back to the
 * daemon. `CrossAffiliationGrantRequest` deliberately carries no affiliation —
 * the institution is read by the daemon from the same sample that produced the
 * warning — because a client-supplied one would let a caller record an
 * acceptance for a triple the user was never shown. See
 * `utils/crossAffiliation.ts`'s `CrossAffiliationOffer`, and
 * `providerAffiliation.test.ts`, which fails if this module ever grows a writer.
 *
 * ⚠ **Parsed structurally rather than imported from `src/api`.** The generated
 * client is regenerated by `just generate-openapi && npm run generate-api`; until
 * that runs, `ProviderDetails` in `types.gen.ts` has no `affiliation` field and a
 * typed read would not compile. {@link readProviderAffiliation} therefore accepts
 * `unknown` and validates the shape itself — which is what a renderer owes a
 * field it is about to make a privacy claim from anyway. When the client is
 * regenerated this stays correct: a total parse over a wider type is still total.
 */

/**
 * Which affiliation this is — mirrored from `ProviderAffiliationKind` in
 * `crates/biorouter/src/providers/base.rs`, whose
 * `the_wire_words_are_the_ones_the_renderer_switches_on` pins these three
 * spellings.
 *
 * ⚠ **There is no `public` member, and that is the shape of the axis.** A public
 * model's affiliation is not a value here, it is the absence of one — `null`
 * from {@link readProviderAffiliation}. Giving "public" a member would invite a
 * badge for it, and a chip reading "no institution" on a public model reads as a
 * *constraint* on the one kind of model that has none of the private tier's
 * protections at all.
 */
export type ProviderAffiliationKind = 'local' | 'institutions' | 'unstated';

/** One institution: the normalised slug, and the registry's name for it if it publishes one. */
export interface AffiliationInstitution {
  /** The slug — what `registry.json`, `baam.html` and every warning print. */
  id: string;
  /** The registry's display name, or absent for an institution it does not publish. */
  display_name?: string | null;
}

export interface ProviderAffiliation {
  kind: ProviderAffiliationKind;
  /** Non-empty exactly for `institutions`. */
  institutions: AffiliationInstitution[];
}

const KINDS: readonly ProviderAffiliationKind[] = ['local', 'institutions', 'unstated'];

/**
 * The affiliation carried by one `ProviderDetails` row, or `null` when there is
 * none to show.
 *
 * ⚠ **`null` is the right answer to three different questions, and drawing
 * nothing is right for all three**: the provider is public (a public model has
 * no third axis — the tier gates already keep it away from private data); the
 * daemon could not resolve an instance; or the payload predates this field. What
 * `null` is NOT is "private with no institution" — that is `unstated`, a real
 * value the daemon only ever sends after a successful resolution, so a failure
 * can never be mistaken for it.
 *
 * ⚠ **An unrecognised `kind` is `null`, never a default member.** A fourth
 * affiliation the daemon learns before this renderer does must render as nothing
 * rather than as whichever of the three the parser happened to fall back to —
 * `local` in particular is the *most* permissive value in DR-26's model, and
 * defaulting an unknown to it would put the blanket-permission chip on a model
 * that never claimed it.
 */
export function readProviderAffiliation(row: unknown): ProviderAffiliation | null {
  if (typeof row !== 'object' || row === null) return null;
  const raw = (row as { affiliation?: unknown }).affiliation;
  if (typeof raw !== 'object' || raw === null) return null;

  const kind = (raw as { kind?: unknown }).kind;
  if (typeof kind !== 'string' || !KINDS.includes(kind as ProviderAffiliationKind)) return null;

  const listed = (raw as { institutions?: unknown }).institutions;
  const institutions: AffiliationInstitution[] = Array.isArray(listed)
    ? listed
        .map((entry): AffiliationInstitution | null => {
          if (typeof entry !== 'object' || entry === null) return null;
          const id = (entry as { id?: unknown }).id;
          if (typeof id !== 'string' || id.length === 0) return null;
          const displayName = (entry as { display_name?: unknown }).display_name;
          return {
            id,
            display_name: typeof displayName === 'string' ? displayName : null,
          };
        })
        .filter((entry): entry is AffiliationInstitution => entry !== null)
    : [];

  // An `institutions` affiliation that names nobody is not renderable: the whole
  // content of the chip is which institutions cover the model. The daemon cannot
  // send one (`InstitutionSet` refuses to be empty, because an empty model set is
  // a subset of every allowlist and would therefore reach every private
  // extension), so this arm only fires on a mangled payload — and drawing an
  // empty institution chip would state a covering agreement that names nobody.
  if (kind === 'institutions' && institutions.length === 0) return null;

  return { kind: kind as ProviderAffiliationKind, institutions };
}

/**
 * How one institution is written: `UCSF` where the registry publishes a name,
 * and the bare slug where it does not.
 *
 * ⚠ **An unpublished institution renders its raw id and is never dropped.** Task
 * 47 rules that an affiliation naming an institution the registry does not
 * publish is a *mismatch* whose id is surfaced; a renderer that hid the row
 * because it had no pretty name would make a real constraint disappear from the
 * one surface the user can see it on. This mirrors `privacy::affiliation::label`.
 */
export function institutionLabel(institution: AffiliationInstitution): string {
  const name = institution.display_name?.trim();
  return name ? name : institution.id;
}

/** `"A"`, `"A and B"`, `"A, B and C"` — a list a person reads, mirroring `join_and`. */
function joinAnd(parts: string[]): string {
  if (parts.length === 0) return '';
  if (parts.length === 1) return parts[0];
  return `${parts.slice(0, -1).join(', ')} and ${parts[parts.length - 1]}`;
}

export interface AffiliationPresentation {
  /** The words on the chip. Short: it sits beside a tier badge. */
  label: string;
  /** The sentence a hover or a screen reader gets. Carries the direction of the axis. */
  title: string;
}

/**
 * How each affiliation reads, as a total map rather than a chain of ternaries.
 *
 * `Record<ProviderAffiliationKind, …>` is the point, exactly as in
 * `PrivacyBadge`'s `TIER`: a fourth affiliation on the wire is a COMPILE ERROR
 * here. A `kind === 'institutions' ? a : b` owes no exhaustiveness, and the
 * branches would then disagree about the new value — which is how a tier once
 * rendered as both Private and Public on two surfaces of one app.
 *
 * ⚠ **Three states a naive mapping renders wrong, and the copy that fixes each:**
 *
 * 1. **`local` is the MOST permissive affiliation, not the narrowest.** A local
 *    model reaches *every* private extension, because no transfer occurs at all
 *    and there is therefore nothing for an agreement to govern
 *    (`privacy::affiliation::compatible` returns for `Local` before any
 *    comparison happens). Rendered as a bare institution-shaped chip beside
 *    `UCSF` it reads as a narrower institution — "UCSF, but even more
 *    restricted" — which inverts the axis. So it does not name an institution at
 *    all: it says where the work happens, and the sentence says nothing leaves.
 * 2. **`unstated` is meaningful, not missing.** Such a model clears only
 *    extensions with no institutional constraint, so it is the least-reaching
 *    private model, and an empty-looking chip would show it as the least
 *    constrained.
 * 3. **`public` is not here at all** — see {@link ProviderAffiliationKind}.
 */
const PRESENTATION: Record<
  ProviderAffiliationKind,
  (institutions: AffiliationInstitution[]) => AffiliationPresentation
> = {
  local: () => ({
    label: 'On this machine',
    title:
      'Runs on this machine, so nothing leaves it and no institution’s agreements are needed. ' +
      'This is the least restricted affiliation: it can reach every private extension.',
  }),
  institutions: (institutions) => {
    const named = joinAnd(institutions.map(institutionLabel));
    return {
      label: named,
      title:
        `Covered by ${named}${institutions.length > 1 ? '’' : '’s'} agreements. ` +
        'Reaching another institution’s private extension is a cross-institutional flow, ' +
        'and needs your approval first. Compliance does not transfer between institutions.',
    };
  },
  unstated: () => ({
    label: 'No stated institution',
    title:
      'This model is private but does not state whose agreements cover it. ' +
      'It can reach private extensions that claim no institution, and every institutional ' +
      'one is a cross-institutional flow that needs your approval.',
  }),
};

/**
 * The words for one affiliation. `null` in, `null` out — so a caller can render
 * the badge from a possibly-absent value without a second guard that could
 * disagree with {@link readProviderAffiliation} about what "absent" means.
 */
export function affiliationPresentation(
  affiliation: ProviderAffiliation | null | undefined
): AffiliationPresentation | null {
  if (!affiliation) return null;
  return PRESENTATION[affiliation.kind](affiliation.institutions);
}
