import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import fs from 'node:fs';
import path from 'node:path';

// Serves the artifact-panel harness against fixtures generated by the Rust tools.
// `PREVIEW_FIXTURE_DIR` is mounted at /fixtures.
export default defineConfig({
  root: path.resolve(__dirname),
  publicDir: false,
  optimizeDeps: {
    // These renderers are imported on demand by DocumentPreview. Pre-bundle
    // them before the harness becomes ready so a cold Vite cache cannot reload
    // the page between fixture clicks and erase the panel's test state.
    include: [
      'pdfjs-dist/legacy/build/pdf.mjs',
      'pdfjs-dist/legacy/build/pdf.worker.min.mjs',
      'xlsx-preview',
      '@aiden0z/pptx-renderer',
    ],
  },
  plugins: [
    tailwindcss(),
    {
      name: 'serve-fixtures',
      configureServer(server) {
        const dir = process.env.PREVIEW_FIXTURE_DIR;
        if (!dir) throw new Error('set PREVIEW_FIXTURE_DIR');
        server.middlewares.use('/fixtures', (req, res, next) => {
          const name = decodeURIComponent((req.url || '').replace(/^\//, '').split('?')[0]);
          const file = path.join(dir, name);
          if (!name || !file.startsWith(dir) || !fs.existsSync(file)) return next();
          res.setHeader('content-type', 'application/octet-stream');
          res.end(fs.readFileSync(file));
        });
      },
    },
  ],
  server: { fs: { allow: [path.resolve(__dirname, '..')] } },
});
