//! @generated by `landing/scripts/build-registry.mjs` — do not edit.
//!
//! Regenerate with `node landing/scripts/build-registry.mjs`; verify with
//! `just check-privacy-registry`, which is wired into `just check-everything`.
//! Rust has no network path to the registry (the only fetch is Electron's
//! `main.ts` `registry:fetch` handler), so without this file the CLI and the
//! daemon can enforce nothing.

/// Extension names (the bundle's `manifest.name`, NOT the registry `id`) that
/// `landing/registry.json` marks `"privacy": "private"`.
pub const PRIVATE_EXTENSIONS: &[&str] = &["cdwagent", "ucsfomopagent"];
