import * as React from 'react';
import { cn } from '../../utils';

/**
 * The progress bar (Astryx §10 "Progress").
 *
 * ONE primitive: an 8px pill track, an accent fill, `width` transitioned at
 * `--dur-med-min` (250ms — the tier whose own comment names "progress fill"),
 * an indeterminate sweep, and `role="progressbar"` ALWAYS.
 *
 * It replaced five hand-rolled bars: `UpdateAvailableModal`,
 * `settings/app/UpdateSection` (byte-identical to it), `settings/usage/UsagePanel`,
 * `ContextWindowIndicator` and `onboarding/OllamaInlineCard`. Between them they ran
 * three track heights (8px, 6px, 4px), four fill vocabularies
 * (`--background-accent`, `--heat-3`, `--background-success`, a raw CSS variable),
 * transitions at 300ms or unspecified, no indeterminate mode at all, and
 * `role="progressbar"` on exactly ONE of the five.
 *
 * ⚠ **The role is why this component exists, and why it is not optional.** Four of
 * the five bars were invisible to a screen reader — an accessibility defect, not a
 * style one. A call site cannot opt out of the role here; it can only supply the
 * label that makes it useful.
 *
 * ⚠ **The geometry and the motion live in authored CSS** (`.br-progress*` in
 * `styles/main.css`), not in Tailwind utilities. Two reasons, both load-bearing:
 * the sweep needs `@keyframes`, which a utility cannot express; and a *newly
 * written* arbitrary utility can silently fail to reach the stylesheet under
 * `BIOROUTER_NO_HMR`, where the renderer runs `watch: { ignored: ['**'] }` — the
 * same signal Tailwind's scanner uses to notice new class strings. The tone fills
 * below stay as utilities only because every one was already generated by the call
 * sites this primitive absorbed.
 */

/**
 * The fill is a PROP, not a fork. Three of the five call sites genuinely mean
 * something other than "accent": a download that succeeded is `success`, a quota
 * gauge rides the accent-derived heat ramp, and both the quota gauge and the
 * context gauge turn `danger` past their limit.
 */
const TONE_FILL = {
  accent: 'bg-background-accent',
  success: 'bg-background-success',
  warning: 'bg-background-warning',
  danger: 'bg-background-danger',
  heat: 'bg-heat-3',
} as const;

/**
 * The track ground follows the tone by default, so the heat gauge keeps its ramp
 * pairing (`heat-0` under `heat-3`) without the call site restating it, and
 * everything else grounds on the one neutral.
 *
 * `track` decouples the two for the one case that needs it: the usage gauge turns
 * its FILL danger past the limit while staying the same heat gauge, so the ramp
 * ground must not follow the fill into neutral.
 */
const TONE_TRACK = {
  accent: 'bg-background-muted',
  success: 'bg-background-muted',
  warning: 'bg-background-muted',
  danger: 'bg-background-muted',
  heat: 'bg-heat-0',
} as const;

export type ProgressTone = keyof typeof TONE_FILL;

export interface ProgressProps extends Omit<React.ComponentProps<'div'>, 'role' | 'children'> {
  /** Current value, clamped to `[0, max]`. Ignored when `indeterminate`. */
  value?: number;
  /** Upper bound of the scale. Defaults to a percentage. */
  max?: number;
  /**
   * "Working, length unknown." Sweeps instead of filling and, per ARIA, drops
   * `aria-valuenow` — a determinate-looking 0% is a worse answer than none.
   */
  indeterminate?: boolean;
  /** Which fill this bar means. */
  tone?: ProgressTone;
  /** Which ground the track paints. Defaults to the tone's own pairing. */
  track?: ProgressTone;
  /** Accessible name. Omit only when passing `aria-labelledby` instead. */
  label?: string;
  /**
   * Minimum rendered fill width, as a percentage of the track. A download that
   * has started but reports 0% should still show that it is a bar; without this
   * the first seconds of every update look like a dead control.
   */
  minVisiblePercent?: number;
  /**
   * Escape hatch for the fill element — extra classes and `data-*` hooks. `style`
   * is withheld: the fill's width IS the value, and a call site that can set it
   * directly can desynchronise the bar from `aria-valuenow`.
   */
  fillProps?: Omit<React.ComponentProps<'div'>, 'style'> & {
    [dataAttribute: `data-${string}`]: string;
  };
}

export function Progress({
  value = 0,
  max = 100,
  indeterminate = false,
  tone = 'accent',
  track,
  label,
  minVisiblePercent = 0,
  className,
  fillProps,
  ...props
}: ProgressProps) {
  const safeMax = max > 0 ? max : 100;
  const clamped = Math.max(0, Math.min(safeMax, Number.isFinite(value) ? value : 0));
  const percent = (clamped / safeMax) * 100;
  const rendered = Math.max(minVisiblePercent, percent);

  const { className: fillClassName, ...restFillProps } = fillProps ?? {};

  return (
    <div
      role="progressbar"
      aria-label={label}
      aria-valuemin={0}
      aria-valuemax={safeMax}
      // ARIA: an indeterminate progressbar has NO `aria-valuenow`. Reporting 0
      // would announce a stalled download that is in fact running.
      aria-valuenow={indeterminate ? undefined : clamped}
      className={cn('br-progress', TONE_TRACK[track ?? tone], className)}
      {...props}
    >
      <div
        className={cn(
          'br-progress__fill',
          indeterminate && 'br-progress__fill--indeterminate',
          TONE_FILL[tone],
          fillClassName
        )}
        style={indeterminate ? undefined : { width: `${rendered}%` }}
        {...restFillProps}
      />
    </div>
  );
}
